spring.application.name=bms

server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/GDdrive?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
# Enable security path debug if needed or default options
spring.main.allow-bean-definition-overriding=true
